FStarLang/karamel

- README.md
I couldn't push that directly...
> Fix opam package 'process' version

- parser/Lexer.ml
> Adding digits to bundles

- kremlib/C.fst
> Expose store32_be and load32_be in C.fst, already defined in kremlib.h

- kremlib/kremlib.h
From https://bugzilla.mozilla.org/show_bug.cgi?id=1396301
The patch in https://bugzilla.mozilla.org/show_bug.cgi?id=1396301 doesn't look correct (it would brake Windows). But this should do the trick.
> Add FreeBSD support

- kremlib/C.Loops.fst
- src/Simplify.ml
- test/Makefile
- test/TotalLoops.fst
A total "do-while" loop to be extracted to C. This could help avoid the use of total recursive functions in Low*.
> Total loops

- include/kremlin/internal/target.h
- kremlib/c/fstar_int16.c
- kremlib/c/fstar_int32.c
- kremlib/c/fstar_int64.c
- kremlib/c/fstar_int8.c
- kremlib/c/fstar_uint16.c
- kremlib/c/fstar_uint32.c
- kremlib/c/fstar_uint64.c
- kremlib/c/fstar_uint8.c
> Added KRML_HOST_SNPRINTF. Fixes #106.

- .merlin
- README.md
- _tags
- kremlib/C.Failure.fst.hints
- kremlib/C.String.fst.hints
- kremlib/C.fst.hints
- kremlib/TestLib.fsti.hints
- lib/Utils.ml
- parser/Lexer.ml
- runtime/WasmSupport.fst.hints
- src/Kremlin.ml
- src/Warnings.ml
Was https://github.com/FStarLang/kremlin/pull/143
> Migrate from ulex to sedlex

- include/kremlin/internal/types.h
- kremlib/c/fstar_uint128_gcc64.h
> Fix build on ppc64le

- src/Helpers.ml
Needed for https://github.com/project-everest/hacl-star/issues/232
> Allow variable elimination for more Lib.IntVector functions

- book/LowStar.fst
- test/HigherOrder2.fst
- test/HigherOrder3.fst
> Fixes for FStarLang/FStar#1905

- src/GenCtypes.ml
This PR fixes #188. I have also tested re-generating the HACL* snapshot and it remains unchanged.
> GenCtypes: Fix binding genration for unsupported types

- Makefile
- kremlib/Makefile
Replace make with $(MAKE) and look for bash along PATH.
> FreeBSD Port

- book/tutorial/Makefile
- test/Makefile
See https://github.com/FStarLang/FStar/pull/2389
> fix --extract settings

- src/Karamel.ml
- src/Simplify.ml
- test/FunctionalUpdate.fst
- test/Makefile
This fixes #249. I added a lot more cases, and a few more cases for cosmetic updates.
> Fixes for functional updates

- src/Simplify.ml
This reverts commit e769065d1f18c6efa8dc628e25cfdaabd94294a5.
@857b heads-up: your change broke HACL*, so need to investigate...
> Revert "Unconditionally simplify trivial let"

- .github/workflows/linux-x64-hierarchic.yaml
- src/InputAstToAst.ml
- test/Literal.fst
@pnmadelaine I came up with a shorter test case
This fixes #269
> Strip leading zeroes from constants

- test/Makefile
> Disabling indexed effects reification extraction test

- book/Introduction.rst
Missing occurence during renaming in the tutorial
> Kremlin -> KaRaMeL

- krmllib/dist/generic/FStar_Pervasives.h
- krmllib/hints/C.Endianness.fst.hints
- krmllib/hints/C.Failure.fst.hints
- krmllib/hints/C.Loops.fst.hints
- krmllib/hints/C.String.fst.hints
- krmllib/hints/C.String.fsti.hints
- krmllib/hints/C.fst.hints
- krmllib/hints/FStar.Krml.Endianness.fst.hints
- krmllib/hints/LowStar.Lib.AssocList.fst.hints
- krmllib/hints/LowStar.Lib.LinkedList.fst.hints
- krmllib/hints/LowStar.Lib.LinkedList2.fst.hints
- krmllib/hints/Spec.Loops.fst.hints
- krmllib/hints/TestLib.fsti.hints
- krmllib/hints/WasmSupport.fst.hints
- src/AstToCFlat.ml
```
Test #1 passed !
jonathan@absinthe:~/Code/everest/hacl-star/dist/wasm (polubelova_precomp_base) $ echo $?
0
```
> Support for compiling buffer casts (e.g. to_const) in WASM

- src/DataTypes.ml
See the commit message -- this adds another rewriting rule that considerably improves the code-quality in HACL*.
HACL* diff: https://github.com/hacl-star/hacl-star/commit/d5a879d74e54de3fbada8aec2d0313a55907398d
HACL* meta-issue: https://github.com/hacl-star/hacl-star/issues/724
(This closes #313)
> Improve peephole optimization for "full matches"

- src/Ast.ml
- src/AstToCFlat.ml
- src/AstToCStar.ml
- src/Builtin.ml
- src/CFlatToWasm.ml
- src/CStar.ml
- src/CStarToC11.ml
- src/Checker.ml
- src/Helpers.ml
- src/InputAst.ml
- src/InputAstToAst.ml
- src/Karamel.ml
- src/PrintAst.ml
- src/Simplify.ml
- src/SimplifyMerge.ml
- src/Structs.ml
This is useful for me as I need the topological order of headers for a script that tries to minimize header inclusion.
> Small fix to debug info

- src/Structs.ml
@R1kM @cmovcc can you confirm this doesn't break anything?
> Fix a typo in the copy-detection check

- .github/workflows/linux-x64-hierarchic.yaml
> Fix commit link on Slack message

- lib/CStarToC11.ml
reported by @karthikbhargavan, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119
> rework zero-initializers to work around ancient GCC bug

- lib/Simplify.ml
What happens is:
- agile functions (like `let block_length  = function SHA3_... -> ... | SHA3_... -> ... | ...`) appear in loop conditions as `i < ... block_length a ...`)
- wasm inlines small helper functions like that aggressively
- the regular hoisting transformation, written for C, thinks that a switch in a loop condition cannot be compiled to C (correct), and also thinks that it's a problem to hoist it, because the loop condition needs to be evaluated on each loop iteration (we don't check whether the things that need to be hoisted contain the index...)
- it shares a warning with the if-then-else node, which has the same problem, EXCEPT there's a workaround for the if-then-else
- we end up with unclosed bindings in the loop test
The fix is to just be ok with it in the case of WASM.
> A quick fix for a WASM-only issue surfaced by @mamonet

- lib/Simplify.ml
> Revert "Substitutions are not type-preserving in C"

- lib/AstToMiniRust.ml
- lib/MiniRust.ml
As part of the Rust extraction of HACL*, several functions are not extracted with messages such as the following:
```
translating Hacl.Streaming.Blake2b_32.reset_raw: Krml.Warn.Fatal("type mismatch;\n  e=(@7).fst\n  t=&'a mut [hacl::hash_blake2b::blake2_params <'a>]\n  t_ret=&mut [hacl::hash_blake2b::blake2_params]\n  x=@7.fst")
```
The reason is that there is a mismatch between the inferred and the expected type, as the inferred type includes explicit lifetime annotations.
This PR aims to provide a best-effort workaround, by comparing types with lifetime annotations erased.
The soundness of this comparison will be left to the Rust borrow-checker, in particular, incorrect cases where there would truly be a mismatch (e.g., because of different lifetimes in `t` and `t_ret`, or because of …
> Attempt to unify implicit and explicit lifetime declarations

- krmllib/hints/C.Endianness.fst.hints
- krmllib/hints/C.Failure.fst.hints
- krmllib/hints/C.Loops.fst.hints
- krmllib/hints/C.String.fst.hints
- krmllib/hints/C.String.fsti.hints
- krmllib/hints/C.fst.hints
- krmllib/hints/FStar.Krml.Endianness.fst.hints
- krmllib/hints/LowStar.Lib.AssocList.fst.hints
- krmllib/hints/LowStar.Lib.LinkedList.fst.hints
- krmllib/hints/LowStar.Lib.LinkedList2.fst.hints
- krmllib/hints/Spec.Loops.fst.hints
- krmllib/hints/TestLib.fsti.hints
- krmllib/hints/WasmSupport.fst.hints
- lib/PrintC.ml
This PR fixes a bug in the previous target attribute PR: it adds quotes around the attribute string.
> Target attribute fix

- lib/AstToMiniRust.ml
- lib/MiniRust.ml
- lib/PrintMiniRust.ml
> Improve visibility of generated Rust definitions; carry top-level comments

- lib/OptimizeMiniRust.ml
The Rust compiler seems to automatically borrow arrays in a split_at/split_at_mut methodcall.
This PR adds a pass to strip unneeded borrows after translation and mutability inference, solving a large number of Clippy warnings in HACL-rs.
The relevant changes are at the very bottom of the file, the rest of the changes remove trailing whitespaces.
> Remove borrows automatically inserted by Rust compiler in split_at

- lib/Simplify.ml
This fixes #478. It could use another set of eyes. I initially marked it unsafe but that prevents to inline something like `[@@CInline] let a' = a in B.free a'`, which is fine.
This F* file:
```fstar
module Inline
module B = LowStar.Buffer
module HST = FStar.HyperStack.ST
module U32 = FStar.UInt32
let read0 (a : B.buffer U32.t) : HST.ST _ (requires fun _ -> False) (ensures fun _ _ _ -> True)
=
B.index a 0ul
let read1 (a : B.buffer U32.t) : HST.ST _ (requires fun _ -> False) (ensures fun _ _ _ -> True)
=
let x = B.index a 0ul in
B.free a;
x
let read2 (a : B.buffer U32.t) : HST.ST _ (requires fun _ -> False) (ensures fun _ _ _ -> True)
=
[@@CInline] let x = B.index a 0ul in
B.free a;
x
let write0 (a : B.buffer U32.t) : HST.ST _ (requires fun _ -> False) (ensures fun _ _ _ -> True)
=
B.upd a …
```
> Simplify.ml: detect EBufFree as a use

- lib/Monomorphization.ml
- lib/PrintAst.ml
> Print locally bound variable names in debug

- include/krml/internal/target.h
Discovered when [testing the Python 3.14 beta](https://github.com/macports/macports-ports/pull/26974) on older versions of macOS.
> Use _mm_malloc() for KRML_ALIGNED_MALLOC on macOS <10.15

- lib/Bundles.ml
This should fix libcrux-mlkem and other testcases
> Fix case of constants, and hide debug info

- misc/cl-wrapper.bat
See discussion here https://github.com/FStarLang/karamel/pull/531#issuecomment-2651069821.
Works on my machine (tm) but some more testing would be good
> cl-wrapper: support Visual Studio 2017 and up by using vswhere

- include/krml/internal/target.h
https://github.com/hacl-star/hacl-star/pull/1028/files but on the upstream repository
> fix clang-cl warnings

- lib/AstToMiniRust.ml
In the Rust extraction, the no_box option allows to remove heuristics to determine which pointer types should be translated to boxes instead of references.
This PR allows disabling this heuristic while explicitly annotating some types as boxed. Instead of resetting the set of boxed_types to empty after the fixpoint computation, it instead removes the base case when the `no_box` option is activated.
> Simplify no_box option

- lib/AstToCStar.ml
- lib/Builtin.ml
- lib/CStarToC11.ml
- lib/Constant.ml
- lib/Simplify.ml
This reverts commit 0f5d5bc435e4c842d0a8055e1fee75b3aa46db0e, reversing changes made to c73b9549d56c1e98c12c2014d347f452674a3bce.
> Revert "Merge pull request #619 from FStarLang/protz/cosmetic"

- test/Makefile
> Enable the -faggressive-inlining test

- lib/Checker.ml
This is @msprotz 's solution for #630.
> Subtype rules for array decay in Checker.ml
