FStarLang/karamel

kremlib/kremlib.h
The masks from both halves of the int should be combined so that eq_mask
always returns all 1s if the numbers are equal or all 0s otherwise.
=> Fix UInt128 eq_mask to always return 2^128-1 or 0

kremlib/kremlib.h
kremlib.h is missing defines for endian-ness on Solaris.
=> Add Solaris defines for Endian-ness macros

.clang-format, kremlib/kremlib.h, src/Driver.ml, test/ExitCode.fst, test/Makefile
@franziskuskiefer can you give this a try?
- The Windows #ifdefs were sketchy: BYTE_ORDER, as far as I know, was defined only in `netsysio.h`, which we were not including, and even then, was defined to be either `_BIG_ENDIAN` or `_LITTLE_ENDIAN` (note the leading underscore), meaning that the #ifdef tests were never executing right ... but apparently, the preprocessor's behavior for #if FOO == BAR when neither BAR or FOO is defined, is to say true, so we were effectively picking LITTLE_ENDIAN... I removed these tests since we don't intend to target Xbox 360
- I also flattened the nested windows tests to either test for msvc (which implies windows), or _WIN32 and clang/gcc ... I wouldn't know what to do in other cases
- the last #else of the (now flat) sequence of cascading #ifdefs errors …
=> Simplify the chain of ifdefs

kremlib/kremlib.h
Don't use variants with IN which expect pointer.
Sorry for the issue. Please see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1405268
https://bugzilla.mozilla.org/show_bug.cgi?id=1419009
Now it should be hopefully right. I have created test program for these macros and I'm getting the same results as on Linux.
=> Fix Solaris defines for Endian-ness

kremlib/krembytes.h
1/ n must be nonnegative
2/ n must not be shifted by more than 32
I request (at least) checking that my rewriting of the loop is equivalent to the previous code. I renamed the loop counter, basically j = (k - 1) - i.
=> Sanitize FStar_Bytes_bytes_of_int

kremlib/krembytes.h, kremlib/kremlib.h
Only in kremlib and krembytes, not in testlib.
The variadic macro requires C99 or later.
=> Replace fprintf(stderr, ...) with a macro (KRML_HOST_EPRINTF)

kremlib/kremlib.h
From https://bugzilla.mozilla.org/show_bug.cgi?id=1439226
Since this library does't include limits.h, SIZE_MAX is undefined. So it requires this header.
=> Android/x86 requires limits.h to use SIZE_MAX macro

kremlib/C.Loops.fst
The measure is not necessarily an integer, but it can be anything allowed in a decreases clause: `lex_t`, following advice from @mtzguido . This is why I propose to change the specification of the general case of total do-while loops, `total_while_gen`, accordingly.
`total_while_gen` is the total do-while loop combinator that is actually extracted to C, from which others are derived (and I will not change the specification of those derived combinators, to avoid breaking existing code.)
Tests show that changing the specification of measures has no impact on extraction, which is expected since measures are ghost data that are not even used while extracting the while loop.
=> More general measure for total while loops

src/Driver.ml
Hello,
this is a small patch I implemented for my local installation of kremlin to allow reading `KRML_HOME` from the environment - similar to how that is possible with `FSTAR_HOME`. I needed this because the assumption that `KRML_HOME` is always in the grandparent directory of the binary doesn't hold true in my environment.
I understand that this might be too specific to my setup as it doesn't seem to cause any problems for others. However I thought the patch might be helpful for various other reasons, so I decided to open a PR.
I apologize if I there are any coding errors - I don't really know OCaml, so I don't expect this to be bullet-proof. I mainly based it on how the `FSTAR_HOME` variable is read in the same file.
I could also not find any contribution guidelines, so I don't know if …
=> Allow reading KRML_HOME from environment

kremlib/Makefile
I thought I had added this some time ago, but it wasn't in master. I need `$(KREMLIN_ARGS)` in these places so that I can add `-fc89` and similar.
=> Added $(KREMLIN_ARGS) to kremlib extraction rules.

include/kremlin/c_endianness.h
I'm using the musl libc in enclaves, which does not define any of the macros currently tested for in [c_endianness.h](https://github.com/FStarLang/kremlin/blob/master/include/kremlin/c_endianness.h). It's a feature of musl, not a bug. The feature detection macros they define are listed in their [manual](https://www.musl-libc.org/doc/1.0.0/manual.html). 
Further, `__linux__` is undefined in our builds of enclave objects. To get around the issue I artificially `#define __OpenBSD__`, but it would be much nicer if we had a different `#define` to select that regardless of the system feature macros.
=> Add macro to select the system's endian.h when __linux__ is undefined.

src/Driver.ml
Nobody seems to be using KRML_HOME, but everybody in Project Everest is using KREMLIN_HOME instead.
=> KRML_HOME -> KREMLIN_HOME

include/kremlin/internal/types.h
stdint.h is required on older compilers to get __int128
=> Include stdint for __int128

include/kremlin/internal/target.h, include/kremlin/internal/types.h, kremlib/c/fstar_uint128.c
GCC <= 4.4 doesn't support the deprecated attribute.
On aarch64 we have unint128 as well.
=> check for aarch64; don't use deprecate on GCC <= 4.4

README.md
wasm 1.0 doesn't support OCaml >=4.08.0 and wasm 1.1 has incompatible APIs
See also #169
=> Update OCaml version upper bound

kremlib/C.String.fst, kremlib/C.String.fsti, kremlib/Makefile
In the everest build only one instance of `abstract` usage came up, in `C.String.fst`.
This PR adds an interface for it, Interestingly, it also brings up the silent leaks in using the `abstract` keyword. For example, the function `v`, `length` etc. were not `abstract`, not sure how they slip through. Writing an interface, I had to make them `val` in the interface (also had to enhance the spec of `length`).
=> Removing `abstract` keyword

include/kremlin/internal/types.h, kremlib/c/fstar_uint128_gcc64.h, kremlib/c/fstar_uint128_struct_endianness.h
Even after #166 got merged, the NSS build is still failing on s390x as mentioned in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1615557
The architecture has [several differences from other arches](https://fedoraproject.org/wiki/Architectures/s390x), but with this change, the build succeeds:
* https://src.fedoraproject.org/rpms/nss/blob/master/f/nss-kremlin-ppc64le.patch
* https://koji.fedoraproject.org/koji/buildinfo?buildID=1463542
=> Fix build on s390x; related to #166

README.md
Closes #169
I also updated the maximum OCaml version to `< 4.10.0` since I could build with `4.09.1`.
=> Update wasm package version

kremlib/c/fstar_uint128_msvc.h
Letting them leak outside of the header can break unrelated code: https://github.com/project-everest/hacl-star/issues/316.
=> Undefine low and high at the end of fstar_uint128_msvc.h

src/Kremlin.ml, test/Makefile
`Makefile.basic` and `Makefile.include` are not always needed, in particular, if KReMLin needs to be called several times in parallel to produce disjoint output. So this pull request adds a new option, `-skip-makefiles`, to not generate them.
=> add -skip-makefiles: do not generate Makefile.basic, Makefile.include

src/CFlatToWasm.ml, src/Kremlin.ml
Attempting to extract code which relies on compiler intrinsics to wasm currently fails as the required functions are not present. This PR fixes this by making sure the wasm functions from the fallback F* implementations of intrinsics are always in scope and that their names can be resolved when extracting code that uses them.
=> Enable the use of intrinsics in wasm code

include/kremlin/internal/target.h
I finally got around to do the [evecrypt rust bindings for Windows](https://github.com/franziskuskiefer/evercrypt-rust/tree/windows-builds). It turned out that it doesn't actually work unless I'm missing something (I wonder if anyone is using hacl on Windows 😬 ).
This PR fixes the Windows builds for me.
=> define KRML_HOST_EPRINTF when building with MSVC

.merlin, _tags, src/GenCtypes.ml
https://github.com/FStarLang/FStar/pull/2247#issuecomment-797409569
Now that the `visitors` package hasn't supported ppxlib-0.22.0 yet, we need to wait for that the happen before merging this commit. In my local setup, I installed manually the patched version for this commit.
=> Migrate OMP to ppxlib-0.22.0

kremlib/js/loader.js
This MR allows setting a custom printer in loader.js, which can also be used to silence output
=> Set custom JS printer function in loader

README.md
A common error during KreMLin compilation seems to be
```
File "src/CFlatToWasm.ml", line 196, characters 18-32:
Error: Unbound constructor W.Ast.LocalTee
```
This occurs when the version of the `wasm` package is too old. More recent versions are not supported with OCaml < 4.08.0.
This PR fixes the README to indicate that KreMLin >= 4.08.0 is required.
=> Update OCaml versions in README

src/Simplify.ml
Meaning their prototypes will be eliminated from public headers, or will go into internal headers (unlikely) rather than show up in the public C API.
This is another big code-quality improvement, to be reviewed after #219
=> Mark projectors and discriminators as private by default

src/Builtin.ml, src/CStarToC11.ml, src/Helpers.ml, test/Makefile, test/SteelNotNull.fst, test/SteelNull.fst
@cmovcc reported failures when attempting to compile C code extracted from Steel. In particular, references to Steel_Reference_null and Steel_Reference_is_null were undefined.
This PR adds support for these two functions, similarly to existing support for LowStar.Buffer.null and LowStar.Buffer.is_null.
=> Support null and is_null Steel functions.

README.md, kremlib/Makefile, kremlin.opam, src/Driver.ml
Fixes Makefile to set the correct environment variables for opam installation.
Also adds a kremlin.opam file for building through opam with the --dev-repo option
=> Fix OPAM build

kremlib/Makefile
When installing through Opam, KREMLIN_HOME was not set during installation, leading to errors when building dist/generic. See for instance https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0cbfb6fe715e61ba1c5ca6e3a0a8eb7cad931522.
=> Add missing KREMLIN_HOME primitives in kremlib/Makefile for opam install

kremlib/Makefile
Extends #225 with a missing primitive
=> Missing KREMLIN_HOME in kremlib Makefile

README.md, kremlin.opam
Fixing the lower bound of wasm=1.1.1 required, and updating the README accordingly to ensure that the installation of opam dependencies fetches compatible versions.
=> Update build instructions to reflect lower bounds on some packages

src/Driver.ml
The use of `--cache_checked_modules` in the call to fstar triggers generation of `.checked.lax` files in all the included paths.
It appears unnecessary and can create issues, typically if a read-only path is included.
=> Remove side effect in driver mode

src/Simplify.ml, test/ExternErased.fst
=> Missing recursive traversal for type-based argument elimination

test/Makefile
This PR uses F*'s `--extract` option to exclude some F* standard library modules from extraction, rather than filtering them out from the Makefile.
This is a stopgap change to unblock Karamel's CI until a more long-term solution is adopted in the F* standard library to never extract those files at the first place.
(A potential solution to the latter problem, as discussed with @nikswamy , @aseemr and @protz , could be to tag entire F* standard library modules with `noextract` , but this needs a change in the F* syntax, which does not currently support module-level attributes.)
=> Steel extraction tests: filter out some F* standard library files

src/Driver.ml
*Scenario 1:* if a user clones the F* repository into a directory whose path contains `opam` (e.g. if the user's login contains `opam`), and compiles it from there, then Karamel will improperly assume that the F* standard library is in `$FSTAR_HOME/lib/fstar` instead of `$FSTAR_HOME/ulib`, claiming that F* was installed by opam.
*Scenario 2:* if a user downloads F* and installs it with `make install`, say into `/usr/local`, then Karamel will improperly assume that the F* standard library is in `$FSTAR_HOME/ulib` instead of `$FSTAR_HOME/lib/fstar`. (F*'s `make install` is indeed used by `opam install fstar`, but not exclusively.)
In both scenarios, such users will not be able to compile HACL* (here in Scenario 1):
<details>
<summary>Click to expand</summary>
```
Unexpected error …
```
=> Properly locate the F* standard library

src/Simplify.ml
In particular, it handle some cases where `let x = ... in x` appears at the end of a function after inlining.
=> Simplify all trivial let-bindings

src/Inlining.ml, src/Monomorphization.ml, test/Abstract.fsti, test/AbstractStruct2.fst, test/AbstractStruct2.fsti, test/AbstractStructAbstract.fst, test/AbstractStructAbstract.fsti, test/AbstractStructParameter.fsti, test/Makefile, test/MonomorphizationCrash.fst, test/MonomorphizationCrash.fsti, test/monomorphization_crash.c, test/monomorphization_crash.h
This fixes #245
Note: the original test was ill-formed, in that it was declaring a C abstract struct but yet declaring a function that had the ability to *construct* values of the struct type without a pointer.
I had to add some custom hand-written files to make the test work -- I assume this is representative of your scenario.
Please confirm this solves the problem you were encountering, thanks!
=> Fixup the interaction of CAbstractStruct, abstract types, and polymorphic equalities

src/CFlat.ml, src/CFlatToWasm.ml
Previously, every module was requesting as imports the entirety of the definitions that has previously been generated. This was sound, but inefficient.
Now, we collect the required "external" definitions in a first phase, and only generate import declarations for those external definitions (function or global) that we need.
=> First attempt at accurate import declarations for WASM modules

src/CStarToC11.ml, src/Helpers.ml, src/Karamel.ml, src/Simplify.ml
- krml is now aware that HACL's vec128_zero, vec256_zero and so on are
zeroes and as such that a for-loop is not needed for compiling
allocations, and a zero-initializer suffices
- an if-statement that is about to compiled as an ifdef can be safely
ignored for the sake of the buffer-hoisting phase
- improved buffer hoisting: if the initial value is a closed term, do
not bother with a copy assignment and lift the array declaration
wholesale
=> Improve code-generation for arrays of vectors.

src/AstToCFlat.ml, src/AstToCStar.ml, src/Inlining.ml
Essentially, these two commits turn non-recoverable code-generation errors into run-time failures on the faulty subexpression. This is particularly useful for compiling some EverCrypt modules: sometimes, a branch will never be taken at run-time in WASM, but still e.g. contains code intended for 256-bit platforms (which WASM isn't).
Rather than raising an exception and failing to compile the whole function, we need turn the faulty branch into a run-time failure, which, by virtue of being never taken at run-time, still makes the whole function work in WASM.
=> Make WASM code-gen more resilient

README.md
Wasm readme.md version constraint was not updated in #267 .
Many thanks for all the work on KaRaMeL!
=> Update readme.md wasm version constraint

include/krml/internal/target.h, src/AstToCStar.ml, src/C11.ml, src/CStar.ml, src/CStarToC11.ml, src/Helpers.ml, src/PrintC.ml, src/Simplify.ml
Right now, this covers the intvector types from HACL*. In the long run, it would of course be nice to define this on the original F* type via an attribute.
No support yet for libintvector.vec512 -- to be added in due time.
=> Generate suitable alignment directives for types that require alignment

src/PrintC.ml
In Microsoft mode, comments are printed with a special syntax so that they can be interpreted by documentation tools. This is actually a good idea, and we should do the same by default, on the basis that if a comment is not proper Doxygen syntax, nothing bad happens.
CCing @duesee and @franziskuskiefer who have requested this
=> Print toplevel comments with Doxygen syntax

include/krml/internal/target.h
Summary: This PR request changes the behaviour of the target.h file for gcc4.4. 
GCC4.4 version complains about `KRML_CHECK_SIZE` and returns an exception ` #pragma GCC diagnostic not allowed inside functions. `
@protz proposed a working solution to have 
```
_Pragma("GCC diagnostic ignored \"-Wtype-limits\"")
```
for this compiler. The PR implements this solution.
=> Adding gcc4.4 exception

src/Builtin.ml, test/Deref2.fst
This PR builds on top of #278, which added specific, more idiomatic extraction for reads on arrays.
The previous PR added a special value, C._zero_for_deref, which serves as a marker for more idiomatic extraction.
This PR marks this value as a builtin, to avoid adding an undefined reference to C._zero_for_deref when C is not in scope.
cc @tahina-pro
=> Add C._zero_for_deref to list of builtins

krmllib/Makefile, src/Builtin.ml, test/Makefile
Following the fix to extraction in FStarLang/FStar#2754, this PR simplifies the build of Steel-related files.
It also tweaks the handling of Steel.Reference. The previous version was only correct because Steel_Reference.krml was always ignored, but led to duplicated libraries when adding it to Builtins.
=> Simplify Steel extraction

.gitignore, Makefile, src/Karamel.ml
This PR extends krml with a new option, called -version, which displays the current version of KaRaMeL (as its current commit hash).
When krml is invoked with the -version, krml exits with return code 0 immediately after printing the version number.
=> Add support for -version flag

src/Builtin.ml
Needed to compile merkle tree as a standalone project with ease
=> Fix a subtle interaction between CAbstractStruct and -library

karamel.opam
There doesn't seem to be a reason to require OCaml < 4.13.0 anymore; the opam package seems to work without this upper bound.
=> Relax OCaml requirements for karamel

include/krml/internal/target.h
I was trying to compile  `dist/gcc-compatible` from the latest HACL* `main` branch with MinGW-W64 (x86_64-w64-mingw32-gcc-11 (GCC) 11.3.0) (to produce a Windows binary release for EverParse, which uses EverCrypt hashing functions), but I failed with error messages complaining about `aligned_alloc` not defined. Thus, I wrote the following C code:
```C
#include "krmllib.h"
#include <stdio.h>
int main() {
char* test = (char*) KRML_ALIGNED_MALLOC(sizeof(char), 1024);
if (test != NULL) {
printf("%d\n", test[2]);
KRML_ALIGNED_FREE(test);
}
return 0;
}
```
which I tried to compile with:
```bash
x86_64-w64-mingw32-gcc.exe -std=gnu11 -I $KRML_HOME/include -I $KRML_HOME/krmllib/dist/minimal test.c
```
There, I got the following error messages:
```
In file included from …
```
=> includes: Fix aligned allocation support for MinGW-W64

.gitignore, krmllib/Makefile
This introduces a RESOURCEMONITOR variable to the Makefile that causes most rules to generate a .runlim file with information about memory usage, cpu time, and more. The results can then be tallied with the `res_summary.sh` script, currently found in the F* repo.
The same idea is applied to the F* and HACL* repos.
---
F* still uses `$(MON)`, will discuss that in the next F* meeting and possibly change the name. Also, the `res_summary.sh` script could be moved to the everest repo.
=> Makefile: introduce resource monitoring with $(RESOURCEMONITOR)

include/krml/internal/callconv.h, include/krml/internal/target.h
This was used chiefly for miTLS. There's one detail about inline and antediluvian gcc versions that moved to target.h
The header will linger around (I have a patch to exclude it from dist/karamel in HACL* forthcoming) until it is removed for good.
=> Do not include callconv.h by default anymore

krmllib/dist/generic/FStar_BV.c, krmllib/hints/C.Endianness.fst.hints, krmllib/hints/C.Failure.fst.hints, krmllib/hints/C.Loops.fst.hints, krmllib/hints/C.String.fst.hints, krmllib/hints/C.String.fsti.hints, krmllib/hints/C.fst.hints, krmllib/hints/FStar.Krml.Endianness.fst.hints, krmllib/hints/LowStar.Lib.AssocList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList2.fst.hints, krmllib/hints/Spec.Loops.fst.hints, krmllib/hints/TestLib.fsti.hints, krmllib/hints/WasmSupport.fst.hints, src/Ast.ml, src/AstToCFlat.ml, src/AstToCStar.ml, src/Builtin.ml, src/CFlatToWasm.ml, src/CStar.ml, src/CStarToC11.ml, src/Checker.ml, src/Helpers.ml, src/InputAst.ml, src/InputAstToAst.ml, src/PrintAst.ml, src/Simplify.ml, src/SimplifyMerge.ml, src/Structs.ml
A node `BufNull t` has type `t*`.
Backwards-compat desugaring of old application nodes in InputAst.ml
=> New internal node for null buffers.

src/GenCtypes.ml
Otherwise, this generates illegal binding code that attempts to take the address of something that doesn't exist (because it is a macro).
=> Don't generate CTypes bindings for C macros

include/krml/internal/builtin.h, include/krml/steel_base.h, include/krmllib.h, src/Builtin.ml, test/Makefile, test/SteelArrayArith.fst
This PR is the companion PR of https://github.com/FStarLang/FStar/pull/2799, which adds a new primitive for restricted pointer comparison.
Most of the documentation is in the corresponding F* module, from karamel's perspective, this PR:
* Adds Steel.ArrayArith.within_bounds_ptr as a primitive builtin, with the signature (post-erasure) that it has in Steel.
* Adds a handwritten implementation of within_bounds_ptr, that is added to builtins.h. This implementation first casts the pointers to uintptr_t, as operations on pointers from different allocation units are undefined according to the C standard (section 6.5.8). Note, I added this function to builtins.h instead of steel_types.h to avoid bringing pthread in the context when concurrency is not required, but there might be a better place …
=> Primitive extraction of within_bounds

test/DataTypesMut.fst, test/ForwardDecl.fst, test/Wireguard.fst
This F* PR fixes a bug in the positivity checker that was not handling mutually inductive types correctly.
https://github.com/FStarLang/FStar/pull/2811
So, a few karamel test cases need no-positivity pragmas.
It seems that one of the examples is meant to be a minimalistic version of WireGuard? It's likely then that the actual F* sources of that application also needs this pragma ... at least until the Low* buffer type gains a positivity attribute.
=> Positivity escape hatches for test cases

Makefile, src/Output.ml
This means you can now do `-add-early-include 'Foo.c."my_header.h"'` and it will truly be at the beginning of the C file.
This also does a little bit of a hardline diet in the pretty printer to not go overboard with blank newlines.
=> Honor fancy syntax for -add-early-include

src/Builtin.ml
This PR is the companion PR of https://github.com/FStarLang/FStar/pull/2834
It extends support added in #325 for primitive extraction of Steel.ArrayArith.within_bounds, to add permissions to the primitive.
=> Update within_bounds builtin with permissions

.nix/karamel.nix, flake.nix
This PR adds a Nix expression to build Karamel.
It does not interfere with the current build process.
Currently the expression is part of the hacl-star repository,
moving it here would make it more visible to interested users and easier to maintain.
=> add Nix support

include/krml/lowstar_endianness.h
AIX (always a big-endian) doesn't have `__BYTE_ORDER__` defined in any of its header files. GCC for this reason defines `__BYTE_ORDER__` in its own header files for AIX. But with XLC compiler, it's not the case.
The issue is exposed while compiling the latest python --> https://github.com/python/cpython/pull/102206
=> Fix endianness issue in AIX

src/CFlatToWasm.ml
The intent seems to be avoiding non-contiguous jump tables. But with so many cases in Spec.Hash.Definitions.hash_alg, we definitely do build a contiguous jump table with more than ten entries. See https://github.com/hacl-star/hacl-star/pull/800
=> Relax dubious heuristic

include/krml/lowstar_endianness.h
Adding `__EMSCRIPTEN__` to endianness.
See https://github.com/cryspen/hacl-packages/pull/394
=> add emscripten to endianness

.docker/build/build-standalone.sh
Replicating project-everest/everparse@46981d5c0025f25fddaf94c7848a4bceac82795b
Some secrets were not properly scrubbed away from logs. This PR does so.
(Those secrets have been rotated since.)
=> CI security

.nix/karamel.nix
Fix Nix build after changing the build system from `ocamlbuild` to `dune` in #212.
=> Fix Nix build

.docker/build/install-other-deps.sh, .gitignore
Otherwise this removes many more lines, causing some warnings. Abridged diff:
```diff
authors: "Jonathan Protzenko <jonathan.protzenko@gmail.com>"
-homepage: "https://github.com/fstarlang/karamel"
license: "Apache-2.0"
depends: [
"ocaml" {>= "4.10.0"}
-  "fstar"
]
-dev-repo: "git+https://github.com/FStarLang/karamel"
-bug-reports: "https://github.com/FStarLang/karamel/issues" 
url {
-  src: "https://github.com/FStarLang/karamel/archive/refs/tags/v1.0.0.zip"
```
The warnings in F* CI:
opam install --deps-only ./karamel-nofstar.opam
[WARNING] Failed checks on karamel-nofstar package definition from source at git+file:///home/opam/FStar/karamel#master:
error  3: File format error in 'url': missing URL
warning 35: Missing field 'homepage'
warning 36: Missing field 'bug-reports'
Nothing to do. …
=> install-other-deps.sh: stricter regex to only remove fstar dependency

Makefile, book/tutorial/Makefile, krmllib/Makefile, test/Makefile, test/sepcomp/a/Makefile, test/sepcomp/b/Makefile
Hi Jonathan, this patch would allow to save some CI time by building karamel (`make minimal`) in parallel with F* and build the library only later, saving some time (though not much). Do you think it makes sense?
I could do the same thing for `clean`, avoiding the generation of `.depend`.
Also a tiny improvement to prevent against creating empty `.depend`s.
=> Makefiles: allow minimal build and cleaning without F*

krmllib/Makefile
The makefile was wrongfully creating these files via the touch command, which meant to just update the timestamp. Use -c to prevent creation of files with this rule.
Also, for the modules which we do not want to extract, use --extract to leave them out of the dependency analysis, so we do not need to ignore them with the -bundle flag (which would also now fail, given that they do not exist).
I added the FStar.Stubs namespace to the list, as I will introduce that in soon-to-come F* PR.
=> krmllib: Makefile: fix ignore of non-extracted modules

src/Monomorphization.ml, test/MutualStruct.fst
What is the criterion for KaRaMel to properly extract, and C to properly compile, mutually recursive structures?
This PR adds a few test cases that give some answer to this question: as @msprotz said, when defining mutually recursive F* records, say `x1`, `x2`,..., `xn`, in this order, if `i < j <= k`, then `xi` can appear in the types of the fields of `xj`, but `xk` can appear in the types of the fields of `xj` only under `ref` or some pointer type.
=> Some extraction tests for mutually recursive structs

test/ctypes/Makefile
Got an everest green with this.
=> tests: ctypes: fix build breakage, use ctypes.foreign and -thread

krmllib/hints/C.Endianness.fst.hints, krmllib/hints/C.Failure.fst.hints, krmllib/hints/C.Loops.fst.hints, krmllib/hints/C.String.fst.hints, krmllib/hints/C.String.fsti.hints, krmllib/hints/C.fst.hints, krmllib/hints/FStar.Krml.Endianness.fst.hints, krmllib/hints/LowStar.Lib.AssocList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList2.fst.hints, krmllib/hints/Spec.Loops.fst.hints, krmllib/hints/TestLib.fsti.hints, krmllib/hints/WasmSupport.fst.hints, src/Ast.ml, src/AstToCStar.ml, src/Builtin.ml, src/C11.ml, src/CStar.ml, src/CStarToC11.ml, src/Common.ml, src/DataTypes.ml, src/Diagnostics.ml, src/Helpers.ml, src/InputAstToAst.ml, src/Monomorphization.ml, src/PrintAst.ml, src/PrintC.ml, src/Simplify.ml
@tahina-pro can you confirm this works for you?
With SteelC now generating anonymous unions, krml needs to consider anonymous union type declarations in the phase that:
- emits type declarations, while
- monomorphizing them, and
- emitting forward declarations in case there is mutual recursion
- and preserving the order so long as the declarations are referred to behind pointers.
=> Bring anonymous unions into the data type monomorphization / reordering phase

include/krml/internal/target.h
This PR does a simple fix (suggested by @protz) to fix the unused-but-set-variable warning on loop indexes in unrolled loops that use the macros in target.h.
=> Void loop index to avoid unused-but-set-variable warning

krmllib/js/loader.js, lib/CStarToC11.ml
this was caught by the everest build because the osx does not seem to mind the prototype discrepancies
=> proper treatment of inline/noinline on externals

include/krml/internal/target.h, krmllib/dist/generic/FStar_UInt_8_16_32_64.h, krmllib/dist/minimal/FStar_UInt_8_16_32_64.h, krmllib/dist/uint128/FStar_UInt_8_16_32_64.h, lib/CStarToC11.ml
It's kind of inevitable, so doing it on a per-function basis. Those will be removed at link-time.
=> Surround static KRML_NOINLINE declarations with pragmas to disable unused function warnings

include/krml/internal/target.h, krmllib/dist/generic/FStar_BV.c, krmllib/dist/generic/FStar_BV.h, krmllib/dist/generic/FStar_UInt_8_16_32_64.h, krmllib/dist/generic/libkrmllib.def, krmllib/dist/minimal/FStar_UInt_8_16_32_64.h, krmllib/dist/uint128/FStar_UInt_8_16_32_64.h, lib/CStarToC11.ml
This PR simplifies the KRML_NOINLINE fix for masking functions to use the attribute "unused" instead of pragmas.
=> NOINLINE improvement

krmllib/dist/generic/FStar_BV.c, krmllib/dist/generic/FStar_BV.h, krmllib/dist/generic/FStar_Issue.h, krmllib/dist/generic/FStar_Monotonic_Heap.h, krmllib/dist/generic/libkrmllib.def, lib/AstToCFlat.ml, lib/AstToCStar.ml, lib/Builtin.ml, lib/CStarToC11.ml, lib/Simplify.ml
Relies on previous work to retain type applications further down the compilation pipeline. Also removes a few silly lines from HACL*.
=> Improve treatment of ignore

krmllib/c/fstar_uint128_gcc64.h
Should this be done in the msvc version as well?
=> Implicit conversions in  fstar_uint128_gcc64.h

lib/Builtin.ml, lib/Simplify.ml
lib/Builtin.ml is a fix for starmalloc and any other project out there that didn't originally take a dependency on LowStar.Ignore
the rest is comments and cleanups in preparation for an overhauled and better structured ignore-insertion phase that is aware of ifdefs
CC @cmovcc FYI
=> Thoughts, comments, and a bugfix for starmalloc

book/AdvancedTopics.rst, lib/AstToCStar.ml, lib/CStarToC11.ml, lib/PrintC.ml, test/Shift.fst
After several days and many discarded designs, I think I have found a reasonable way to i) optimize the generation of integer arithmetic constants and computations (hi @franziskuskiefer, @karthikbhargavan, please take a look at HACL branch protz_shift to see the effects of the change), ii) fix the semantics of right-shift (hi @s-zanella, @polubelova), and iii) in the process of doing so, fix integer conversion warnings for right-shifts (there are still spurious warnings in a lot of places in HACL, but at least that one reported on Slack by @franziskuskiefer in FrodoKEM is now gone).
I know that others have encountered #102 in one form or another in the past, so my request to @tahina-pro: can you please take a careful look at this PR and tell me whether you believe this compilation scheme …
=> Address long-standing issue with right shift -- fixes #102

.nix/karamel.nix, Makefile
Currently, when F* and KaRaMeL are built using Nix and `FSTAR_HOME` properly set to the result of the F* derivation:
1. `krml -version` provides us with an empty string;
2. the header of extracted files contains the following line: `F* version: <unknown>`;
3. the header of extracted files contains the following line: `KaRaMeL version: <unknown>`.
About 1. and 2.: the Nix build environment source of KaRaMeL is just the content of the specified revision of the git repository, not the git repository itself. Thus, `make lib/Version.ml` does not work properly, as `git rev-parse HEAD` fails. Fixed by adding the `GIT_REV` environment variable during a Nix build, and using it if `git rev-parse HEAD` fails.
About 3.: in `lib/Driver.ml`, if `$FSTAR_HOME` does not point to a git repository (e.g. …
=> Fix Nix build: krml -version is empty, incorrect extracted files header

.docker/standalone.Dockerfile
Should fix the CI breakage if no F* images are present.
=> ci: standalone.Dockerfile: add missing dependencies

lib/Ast.ml, lib/CStarToC11.ml, lib/Checker.ml, lib/Helpers.ml, lib/Monomorphization.ml, lib/MonomorphizationState.ml, lib/PrintC.ml, lib/Simplify.ml, lib/Structs.ml
Rust makes a proper distinction between arrays and pointers, and functions in Rust can return arrays (by value). This can of course be optimized into a caller allocating space for the array (known at compile-time) and the callee copying its return value into the destination address.
There was already a phase for that in krml (used for mitls, a long time ago, but also for the wasm backend) so it was mostly a matter of tweaking it.
=> Generalization of the "pass by ref" for the case where functions are returning arrays (not pointers)

dune-project
PR #364 moved the Dune minimal version requirement in `dune-project` to 3.7, but this prevents Karamel from being built on Windows with fdopen's deprecated repository, which only supports Dune up to 3.5, and which is currently the only known method to build native Windows executables for Everest components.
This PR sets the requirement to Dune 3.5. It works at least on my Windows machine.
=> Use Dune 3.5

lib/Ast.ml, lib/AstToCFlat.ml, lib/Builtin.ml, lib/Bundle.ml, lib/CFlatToWasm.ml, lib/CStarToC11.ml, lib/Checker.ml, lib/DataTypes.ml, lib/Diagnostics.ml, lib/GenCtypes.ml, lib/GlobalNames.ml, lib/InputAst.ml, lib/InputAstToAst.ml, lib/Monomorphization.ml, lib/PrintAst.ml, lib/Simplify.ml, lib/SimplifyMerge.ml, lib/Structs.ml, lib/lib/KList.ml, src/Karamel.ml
This PR cleans up the `KList` module by using newly-introduced `Stdlib.List` utilities:
- `KList.filter_map` is `Stdlib.List.filter_map`
- `KList.map_flatten` is `Stdlib.List.concat_map`
- `KList.make` is `Stdlib.List.init` **except for the side-effects** (I think this is fine but you might want to check this.)
- `KList.find_opt` is `Stdlib.List.find_map`
- `KList.assoc_opt` is `fun k -> Stdlib.List.assoc (Some k)`
Additionally:
- We get rid of `KList.max` and `KList.min` which are easily written using the already-existing `KList.reduce`.
- Some functions will become available in OCaml 5.1 and are commented as such to help future cleanup.
- We rewrite `KList.fold_lefti` as a special case of `List.fold_left`, hopefully making it more readable.
- We rewrite `KList.last` as a recursive …
=> Cleanup the `KList` module

lib/DataTypes.ml, test/MatchNested.fst
this PR (hopefully) addresses a performance / non-termination problem I was having.
I had a problematic program contains many matches where the scrutinee itself contains nested matches (eg `match match match match match match t with ... with ... with ...`). in reduce_full_matches, it reduces the scrutinee and the branch, then if it can't apply case-of-constructor it backtracks, which ends up having to reduce the scrutinee and branch again separately. in my case with lots of nested matches, this seemed to be taking exponential time in the number of nested matches.
=> remove backtracking in `reduce_full_match`

.nix/karamel.nix
This PR ships the `krml` library in the Nix build, so that it can be consumed by other OCaml packages through Nix.
=> feat(nix): expose `krml` library in `passthrough`

lib/DataTypes.ml, test/StructWithUnitIsUnit.fst, test/TwoUnitsAreOne.fst
As it turns out, the case where a struct is made of *only* ghost fields had previously never been exercised before. This is easily fixed with another nano-pass that performs a little bit of cleanup.
=> Nano-pass: remove empty records

lib/AstToMiniRust.ml, test/Rust6.fst
This is a small tweak to the existing fallback for the case when a sub operation appears in subexpression position (e.g., as an argument to a function call), which happens in HACL* when using inline_for_extraction for sub operations.
The previous behavior was to always take a mutable borrow on the range created by the subbuffer. When using const buffers, this led to borrow-checking issues, where we tried to take a mutable borrow on a shared borrow. This PR slightly tweak this behavior to check (based on the argument type) whether the buffer argument is const. In this case, it is extracted as a shared borrow.
A small example (Rust6) showcases the problematic pattern, which is present in HACL*'s Ed25519/P256/K256 when using precomputed tables, where the function `f` was previously extracted …
=> Extend Rust extraction support for ConstBuffer in subexpression positions

include/krml/internal/target.h, lib/AstToMiniRust.ml
Helpful for debugging hacl-rs compilation warnings
=> Print split warnings with the function that they're in

lib/AstToMiniRust.ml, lib/PrintMiniRust.ml, src/Karamel.ml
Support for macro-based loop unrolling, relying on a proc macro (currently defined in HACL*).
=> Protz rs unroll

.docker/hierarchic.Dockerfile, .docker/standalone.Dockerfile
following https://stackoverflow.com/a/73949524
This is confirmed to work with EverParse (see project-everest/everparse@4c532e5bca021c8c5c4293b3b7d7e2f57e22cbe4) : sphinx now correctly runs and updates EverParse's user manual.
=> CI for user manual: install pytz

lib/Simplify.ml
So today I (re-?) discovered that substitutions are not type-preserving in C.
```
int x[1];
int *px = x;
int **ppx = &px;
```
substituting px away breaks typing:
```
int x[1];
int **ppx = &x;
```
does not work, because `&x` has type `(int*)[1]`. In other words, the intermediary declaration `px` forces array decay, which otherwise does not happen (because array decay is in function argument position, or assignment position). This makes sense: `&x` represents only a single level of indirection, not two.
The C compiler will flag this and reject the program. But of course we don't want to generate C code that doesn't compile, so rather than introduce a cast, we simply refuse to substitute away variables that force array decay.
This was only triggered by Eurydice, because due to a fortuitous …
=> Substitutions are not type-preserving in C

lib/Structs.ml
#431 introduced a stronger monomorphization, which in particular rewrites occurences of Steel_SpinLock_lock () into Steel_SpinLock_s_lock. This in turn leads to escaping the address-passing semantics of locks.
This PR fixes this by adding Steel_SpinLock_s_lock to the specific handling of locks.
=> Fix spinlock extraction due to stronger monomorphization

lib/AstToMiniRust.ml
This PR extends support for type abbreviations to support aliases to other types that are lifetime parametric.
Consider the following output, which is similar to what happens in HACL-rs
```rust
pub type uint8_4p <`a> = &'a mut [u8];
pub type bufx4 = uint8_4p;
```
This will not compile, as both `bufx4` and `uint8_4p` should be indexed by a lifetime.
This PR will detect that `uint8_4p` is parametric in a lifetime, and therefore generate `pub type bufx4 <'a> = uint8_4p <'a>;`.
=> Extend support for type abbreviations

lib/PrintMiniRust.ml
Small code quality improvement to Rust generation: so far, the return type of a function was always printed (through the `-> ty` notation).
When it is unit, it is not needed and raises linter warnings.
This PR special-cases the return type unit during printing of function declarations.
=> Do not generate Rust return type when it is unit

include/krml/internal/target.h
When adding `__attribute((always_inline))` to a function, the compiler complains if it is not also marked with `inline`.
This PR changes the `KRML_MUSTINLINE` macro to always add `inline` as well.
=> always_inline seems to also require inline

test/.hints/Underspec.fst.hints, test/Underspec.fst
Hi Jonathan, this PR adds a test for `mul_underspec` to test the patch in https://github.com/FStarLang/FStar/pull/3349.
I had to use this `irreducible` four definition to prevent the normalizer from simpliyfing the operation, so we actually try to extract it. Not sure if you have a better way?
I don't know if this is of much value as-is, maybe we can beef it up with other operations/widths too. For that I think `main` would look like
```fstar
if not (test1 ()) then 1l else
if not (test2 ()) then 1l else
if not (test3 ()) then 1l else
...
```
or something similar.
=> (RFC) Add a test for mul_underspec

lib/PrintMiniRust.ml
Follow-up of #462 , addresses https://github.com/FStarLang/karamel/pull/462#discussion_r1723654710
=> Comment why unit-erasure is needed in MiniRust

lib/PrintMiniRust.ml
As described in title, when creating a struct, instead of generating, e.g., `{ mu: mu }`, generate `{ mu }`
=> Use field-init shorthand syntax when creating structs

lib/MiniRust.ml, lib/OptimizeMiniRust.ml, lib/PrintMiniRust.ml
Another cosmetic change: when applicable, use the assign-op pattern on assignments where the rhs is a binary operator.
For instance, `x = x & y` becomes `x &= y`
=> Rust backend: Rewrite according to the assign-op pattern

lib/OptimizeMiniRust.ml
Generalization of #465 . The Rust compiler actually automatically inserts borrows and derefs for methodcalls, and derefs for fields.
=> Generic auto-borrowing for method calls and auto-deref for fields

lib/AstToMiniRust.ml, lib/Constant.ml, lib/OptimizeMiniRust.ml, lib/OutputRust.ml, lib/PrintMiniRust.ml
A few additional cosmetic changes to the Rust backend, following Clippy:
* Rewrite nonminimal boolean expressions (e.g., ! (x == y) becomes x != y)
* Print else if on the same line for nested if/then/else
* Use vec! for vector creation, with a small tweak for repeats of size 1
* Reintroduce the unused_mut warning, which was solved by mutability inference
=> Cosmetic changes to Rust backend

lib/Ast.ml, lib/DataTypes.ml, lib/Helpers.ml, lib/InputAst.ml, lib/InputAstToAst.ml, lib/Simplify.ml, lib/SimplifyWasm.ml, test/InlineLet.fst, test/Makefile
This is an alternative to #469. In https://github.com/FStarLang/FStar/pull/3418 (which this depends on to really work), I am making F* interpret the `CInline` attribute for local definitions too, and setting a flag in the relevant binder in the extracted krml AST. This PR makes krml pick it up and trigger inlining.
For instance, this function:
```fstar
let foo (x:UInt32.t) =
[@@CInline] let y = x in
[@@CInline] let z = x in
y `add_underspec` z
```
Now extracts to
```c
uint32_t Inline_foo(uint32_t x)
{
return x + x;
}
```
Some questions:
0- Does it make sense to reinterpret `CInline`? I could add another attribute if not.
1- I think this may require bumping the krml ast version? I see the comment about adding constructors only at the end, but I suppose adding a field to a record is just a …
=> Using `CInline` to inline local letbindings

lib/AstToMiniRust.ml, lib/OptimizeMiniRust.ml
As described in the title. There currently is some special-casing to avoid move-out when, e.g., accessing an array of non-Copy elements.
This PR extends what is considered as a non-Copy element to also consider pointer holding structs.
=> Prevent move-out on pointer holding structs

include/krml/internal/target.h
This change avoids warning/error when compiling with Oracle Studio by adding appropriate attributes for the inline enforcement. The `__SUNPRO_C` internal define  is documented in the Studio compiler man page for the `cc` command. The attribute values themselves are documented in https://docs.oracle.com/cd/E77782_01/pdf/E77788.pdf (section 2.10)
While the `__SUNPRO_C` define has a distinct value for every version, for this change I am assuming fairly modern version, i.e. 12.x, so the value is not checked. Let me know if that's okay.
=> specify inline related attribute for Oracle Studio compiler

include/krml/internal/target.h
Another change for Oracle Studio compiler - this time adding the support for the deprecated attribute. Again, assuming fairly modern version of the compiler (>=12.x).
=> specify deprecated attribute for Oracle Studio compiler

lib/OptimizeMiniRust.ml, lib/OutputRust.ml, test/Makefile
With the recent addition of mutability inference, accesses to top-level constants do not require mutable borrows anymore, which was the cause of the const_item_mutation warning.
Additionally, this PR adds a micropass to simplify the `deref_addrof pattern`, e.g., `*&[]`
=> Rust backend: allow const_item_mutation warning, simplify deref_addrof pattern

krmllib/Makefile
In support of ~https://github.com/FStarLang/FStar/pull/3549~ https://github.com/FStarLang/FStar/pull/3552, which makes FStar.IO an interface which is conceptually more correct.
I don't think this would have many users at the C level and would maybe just remove it from this list... but it is exposed, and has an implementation in krmllib/dist/generic/fstar_io.c.
This is motivated by the new F* build, I'm trying to get some smaller pieces in independent PRs.
---
Btw I read this comment:
https://github.com/FStarLang/karamel/blob/8c3612018c25889288da6857771be3ad03b75bcd/krmllib/Makefile#L50-L55
I'm not sure I understand it but F* can now be queried for exactly that by `fstar.exe --locate_lib`.
=> lib: Makefile: FStar.IO.fst is now FStar.IO.fsti

Makefile
This line gives some bad errors whenever ocamlfind is not in the
PATH or the visitors package is not installed, and may carry on
with the Makefile regardless of that failure (attempting to include
/Makefile.preprocess along the way).
$ make
make: ocamlfind: No such file or directory
Makefile:2: /Makefile.preprocess: No such file or directory
make: *** No rule to make target '/Makefile.preprocess'.  Stop.
This patch makes the Makefile provide more helpful errors in both these
situations:
$ make
make: ocamlfind: No such file or directory
Makefile:7: *** "'ocamlfind query' failed, please install OCaml and put it in your PATH.  Stop.
$ make
ocamlfind: Package `visitors' not found
Makefile:11: *** "'ocamlfind query visitors' failed, please 'opam install visitors'.  Stop.
=> Makefile: improve confusing errors in inclusion

lib/UseAnalysis.ml, test/KrmlTrue.fst, test/Makefile
before, when discovering that `x` is unused in `let x = e1 in e2` , we would unconditionally push `KRML_IGNORE` down `e1` (possibly beneath multiple layers of let-bindings)
now, instead, we either do `let x = KRML_IGNORE(e1) in e2` is `e1` is a value, otherwise, we do `let x = e1 in KRML_MAYBE_UNUSED_VAR(x); e2`
=> Change the criterion for KRML_IGNORE vs KRML_MAYBE_UNUSED_VAR

.docker/hierarchic.Dockerfile, .docker/standalone.Dockerfile
Since Ubuntu 23.10 is EOL, and 24.04 does not work with F* CI, the latter was reverted to Ubuntu 22.04, see FStarLang/FStar#3615 
This PR adapts to this change.
=> Temporary CI fixes due to FStarLang/FStar#3615

lib/Structs.ml
The phase that is in charge of rewriting array-returning functions into outparam-style functions was a little bit over-zealous. Notably, in the case of a slice index operation, when the type of elements in an array already, MIR is already aware that such an operation will return a pointer, and there is no need to give is the whole "let's copy the result in an out-array" treatment.
This was the cause of a lot of pain on the Eurydice side, so fixing this properly here, with a note that this might be an instance of a more general pattern, which would avoid hardcoding something so specific.
=> Improve the treatment of abstract, polymorphic functions that are used with array types

lib/InputAstToAst.ml
I'm quite surprised we never needed this before. I found it useful to document that a particular branch is statically unreachable, via the use of false_elim. Some other parts of HACL* do:
```
let () = false_elim () in
LowStar.Failure.failwith "statically unreachable"
```
which is slightly overkill, so I added support for false_elim, extracting as a regular call to KRML_ERROR, with a notice that the code was provably unreachable
=> Support false_elim

include/krml/internal/target.h
I didn't expect #504 to be merged quickly.
Since we are using `mm_malloc.h`, in this case it is better to apply `_mm_free()` to `KRML_ALIGNED_FREE`.
=> Add LEGACY_MACOS macros, use _mm_free() for KRML_ALIGNED_FREE on macOS <10.15

lib/DataTypes.ml
This fixes https://github.com/AeneasVerif/eurydice/issues/107 and I do not have a regression on everest
=> Eliminate empty struct *definitions*

lib/Checker.ml, lib/Monomorphization.ml, lib/MonomorphizationState.ml
From the diff:
We need to renormalize entries in the data type monomorphization map for the Checker module. For
instance, the map might contain `t (u v) -> t0` and `u v -> u0`, but at     this stage, we will have a type error when trying to compare  `t (u v)` and     `t u0`, since the latter does not appear in the map.
This fixes https://github.com/AeneasVerif/eurydice/issues/100
=> Renormalize data types properly

lib/CStarToC11.ml
Previously, we operated in a model where the amount of heap memory was infinite.
For the first time (to the best of my knowledge), a piece of code started leveraging the "partial" allocation functions in the Low* libraries, here: https://github.com/hacl-star/hacl-star/pull/1007. Partial allocation functions (also known as fallible) may return NULL, and the user must check that the result is non-null before doing anything with it.
This NULL-check was defeated by the fact that the initial value for the heap allocation (as provided in the Low* model) had to be compiled to an assignment (in C) that operates after the malloc but before the user got a chance to check for NULL...
The fix is simply to always guard such assignments (for the initial value to be stored in the heap allocation) to be …
=> Perform null-checks when assigning initial value of heap allocations

krmllib/hints/C.Endianness.fst.hints, krmllib/hints/C.Failure.fst.hints, krmllib/hints/C.Loops.fst.hints, krmllib/hints/C.String.fst.hints, krmllib/hints/C.String.fsti.hints, krmllib/hints/C.fst.hints, krmllib/hints/FStar.Krml.Endianness.fst.hints, krmllib/hints/LowStar.Lib.AssocList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList.fst.hints, krmllib/hints/LowStar.Lib.LinkedList2.fst.hints, krmllib/hints/Spec.Loops.fst.hints, krmllib/hints/TestLib.fsti.hints, krmllib/hints/WasmSupport.fst.hints, lib/Ast.ml, lib/AstToCFlat.ml, lib/C11.ml, lib/CStar.ml, lib/CStarToC11.ml, lib/DataTypes.ml, lib/PrintAst.ml, lib/PrintC.ml
Now that we allow choosing values for enum constants, there are two compilation schemes for enums (i.e., data types where no constructor takes arguments).
- C11 enums, i.e., `typedef enum { A = 0xff, ... } t;`. These are mandated to have type `int` in C11; C23 allows choosing the width, but we don't yet assume C23. We assume `sizeof int == 4` and error out if any of the user-chosen constants exceed the range of `int`.
- Macros. We cannot represent arithmetic on enum constants, so there are no issues about integer promotions, or a constant being sign-extended for the wrong reasons. We just print out integer literals, and try the first type that fits all possible values for the enum type, with a preference for unsigned types.
This fixes AeneasVerif/eurydice#123
=> Improved compilation scheme for enums.

.docker/build/install-deps.sh
Path to script was wrong, causing a confusing error with sudo
=> install-deps: fix standalone CI

lib/OptimizeMiniRust.ml
Slight refinement of the nanopass removing trailing units in the Rust backend.
Consider the following code
```rust
let x: u32 = 0;
()
```
With the previous version, the nanopass would have rewritten this code into `0`, leading to typechecking failures in Rust.
This PR tweaks the pass to only perform the rewriting when the previous expression has type unit.
=> Fix Rust cosmetic pass removing trailing units

.nix/karamel.nix, Makefile, README.md, book/Setup.rst, book/tutorial/Makefile, book/tutorial/Makefile.include, krmllib/Makefile, lib/Driver.ml, lib/Options.ml, src/Karamel.ml, test/Makefile, test/sepcomp/a/Makefile, test/sepcomp/b/Makefile
With this PR krml will no longer do anything fancy to find an "FSTAR_HOME" or the F* executable: it will use the PATH. It can be overriden with the new `-fstar` option though. The library can be located by just asking F*.
All the makefiles set `FSTAR_EXE ?= fstar.exe` and pass `-fstar $(FSTAR_EXE)` to krml, so one can set FSTAR_EXE instead of placing F* in the PATH. But this is a convention of the Makefiles.
=> No FSTAR_HOME

.github/workflows/linux-x64-hierarchic.yaml, lib/Bundles.ml, lib/CStarToC11.ml, lib/Output.ml
The dependency analysis was pretty coarse, and only represented dependencies from one "file" to either regular or internal headers. It turns out that the dependencies vary quite widely between that file's public header, internal header, or C implementation.
This was pointed out here: https://github.com/hacl-star/hacl-star/pull/1007#discussion_r1871934044
This revamps the analysis to now distinguish dependencies between { h file, internal/h file, c file } to { h file, internal/h file }.
The net result is a considerably reduced number of #includes in public headers.
=> Revise dependency analysis to be more precise

flake.nix
This PR adds support for building karamel on apple machines using nix.
=> feat(nix): add support for aarch64 linux & mac

lib/AstToMiniRust.ml
This adds support for the missing Pulse builtin `Pulse.Lib.Slice.subslice`.
=> Support Pulse.Lib.Slice.subslice

lib/AstToMiniRust.ml, lib/MiniRust.ml, lib/OptimizeMiniRust.ml, lib/PrintMiniRust.ml
PR in support of scylla, to integrate external (assumed) declarations when transpiling from C to Rust.
This PR translates `DExternal` declarations in Ast to a new `Assumed` node in MiniRust.
In particular, the translation preserves the mutability that was specified by the external declaration, and uses it for the mutability inference in `OptimizeMiniRust`. This behavior is overriden for external, "builtin" definitions.
Assumed definitions are then filtered and not extracted to Rust: Rust clients are expected to provide them directly.
The extraction of hacl-rs from Low* remains the same with this PR.
=> Support Assumed Declaration in MiniRust translation

krmllib/C.String.fst, krmllib/C.String.fsti, krmllib/C.fst, krmllib/LowStar.Lib.AssocList.fst, krmllib/LowStar.Lib.AssocList.fsti, krmllib/LowStar.Lib.LinkedList2.fst, krmllib/TestLib.fsti, krmllib/compat/C.Compat.String.fst, krmllib/compat/C.Compat.fst, krmllib/compat/C.Nullity.fsti, test/Ctypes2.fst, test/Ctypes4.fst, test/DataTypesEq.fst, test/HigherOrder2.fst, test/HigherOrder4.fst, test/Layered.fst, test/LinkedList1.fst, test/LinkedList2.fst, test/LinkedList3.fst, test/Lowlevel.fst, test/MutualStruct.fst, test/NoShadow.fst, test/Rust6.fst, test/Scope.fst, test/TotalLoops.fst, test/Underspec.fst, test/hello-system/SystemNative.fsti, test/sepcomp/b/B.fst, test/sepcomp/b/D.fst
With the script in https://github.com/FStarLang/FStar/pull/3755. Not sure if any of these could be intentional but CI passes.
=> Removing unused modules

lib/Checker.ml
In FStarLang/pulse#326, I am introducing Pulse mutable slices, and I am turning slices into immutable slices. For their C implementation, I am introducing `const` array pointers.
Then, I tried to refine the signature of corresponding memcpy operations so that the source pointer can be `const`. However, Karamel rejects me with:
>  blit requires a non-const pointer
This PR solves this issue by weakening the checks in `lib/Check.ml` to allow immutable source buffers. The destination buffer must still be mutable, though.
Everest green CI: https://github.com/project-everest/everest/actions/runs/13336176953
=> Allow const source buffers for EBufBlit

lib/Driver.ml, lib/Error.ml, lib/Options.ml, lib/Warn.ml, src/Karamel.ml
This patch makes karamel pick, by default, 'cc' from the path as the C compiler. This command can be overriden with the -cc option (taking the name of a program in the PATH, or a full path to an executable), or the CC environment variable (idem).
Since karamel passes specific options to different compilers, there is now logic to detect the flavor of compiler that karamel is talking to (e.g. by looking at `cc --version`).
*MISSING*: MSVC autodetection, and fixing the wrapper script. I don't have enough experience using it to know if we can tweak this script so as to only point it to an executable.
Also I think I should add a way to override the flavor in case autodetection fails.
(If you feel this change is more trouble than it's worth I'm ok dropping it.)
Fixes #529
=> Rework C compiler detection

book/tutorial/Makefile, krmllib/Makefile, test/Makefile, test/sepcomp/a/Makefile, test/sepcomp/b/Makefile
Mostly:
1. For extracting, we can just pass the path of the checked file to
F* instead of doing the hacky substitution and rely on F* to find the
source module.
2. no need to pass --extract when we want to extract a single file
(except for --codegen krml, separate PR incoming for that).
3. Using -o instead of (the now deprecated) --output_deps_to and
--krmloutput.
4. Using -c instead of --cache_checked_modules, and only passing it
when we are actually trying to create a checked file.
Also added some explicit -o flags to make sure F* writes to the desired
target.
(Previous text:
Mostly no need to pass --extract when we want to extract a single file, and we can just pass the path of the checked file to F* instead of doing the substitution.
Also added some explicit --krmloutput flags to make …
=> Simplify Makefiles after F* changes

lib/AstToMiniRust.ml, lib/OptimizeMiniRust.ml
As the translation from Ast to MiniRust is type-directed, translating a Return node needs the return type of the function being currently translated. This PR adds this type to the translation functions (and the mutability inference), and uses it for the EReturn/Return nodes.
It also fixes the translation of a split tree access with a missing `possibly_convert`.
=> Improve the Rust extraction of Return nodes

lib/DataTypes.ml
So I found out while debugging strange header inclusion issues in HACL* that krml only partially hash-consed data type tags. Concretely, if two monomorphized types `option_t` and `option_u` were in the same file Foo, then they would both rely on `typedef enum { Foo_None, Foo_Some } Foo_option_tags;`. However, if a third `option_v` was placed in file Bar, then this time a different declaration would be emitted, namely, `typedef enum { Bar_None, Bar_Some } Bar_option_tags;`.
This doesn't seem like the end of the world, HOWEVER, in the case of HACL*, and following the recent changes to take into account allocation failures in the streaming functor, a whole bunch of monomorphized instances of `option` started popping up across the codebase. Because of the proliferation of tag types, and …
=> Actually hash-cons data type tags

lib/AstToMiniRust.ml
The Ast to Rust translation relies on several heuristics to determine when pointer types should be translated to boxes.
This PR allows users to specify an additional list of types that *must* be translated to boxes.
The behavior for the F* to Rust extraction is left unchanged: this set is initialized to empty.
=> Support for user-provided annotations about box types in Ast to Rust translation

lib/AstToMiniRust.ml, lib/MiniRust.ml, lib/OptimizeMiniRust.ml, lib/PrintMiniRust.ml
Support variable declaration, without any definition associated.
We assume that such variables are identified as a let-binding, where the expression is an `EAny`, but with the type corresponding to the binding.
=> Add support for variable declaration in Rust

lib/C11.ml, lib/CStarToC11.ml, lib/Options.ml, lib/Output.ml, lib/PrintC.ml, src/Karamel.ml
Code generated by krml by default works both in C11 and in C++20 -- the code can be compiled either by a C or a C++ compiler.
For downstream users who do not have C++20, this PR adds a new C++17 mode that generates code compatible with C++17 but *not* with C11. It may be that the code is compatible with C++11 but I have not checked that, so for now, the flag remains C++17.
=> Add a new mode for generating C++17 code

lib/PrintC.ml
Just a pretty-printing nit. I have some other readability improvements in a local branch, wondering if this stuff is useful or just adding noise.
----
This improves the printing so that the operands can break into multiples lines independendently of each other, and of the full expression. This is still not perfect, we could accumulate operands and `flow` them instead of this, but for a one liner it's a nice improvement.
Example, for:
```fstar
let foo (long_name : U64.t) : U64.t =
let open FStar.UInt64 in
(long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name)
-%^ (long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name -%^ long_name)
```
The code goes from
```c
uint64_t foo(uint64_t long_name)
{
return
long_name
- long_name
- …
```
=> PrintC: nit, group operands

lib/AstToMiniRust.ml
As described. Since the return type of several functions can change due to the addition of boxes, we need to preserve as much as possible the expected type throughout the translation.
=> Fix type-directed translation of matches and switches

lib/AstToMiniRust.ml, lib/Helpers.ml, lib/OptimizeMiniRust.ml
This removes un-necessary casts and improves array handling for Scylla.
=> Enhanced treatment of arrays in AstToMiniRust

lib/DataTypes.ml, test/NestedAnonUnions.fst
We ran into this bug today (see testcase). I think this is the fix, the one thing I'm not sure about is whether passing `t2.typ` is correct. It seems like it's meant to be the type of the expression being visited, but I don't understand OCaml visitors well enough to be sure.
=> Add missing recursive calls when anonymizing unions

lib/OptimizeMiniRust.ml, lib/lib/KList.ml, test/Makefile, test/Rustpair.fst
We ran into this issue with the pair returned by `Slice.split`.
=> Handle `let (x, _) = y;`

lib/PrintMiniRust.ml
Not sure how to test this, we hit this with bundles when a monomorphized name is referenced from another bundle.
=> Escape names when using bundles in Rust.

lib/OptimizeMiniRust.ml, lib/PrintMiniRust.ml, test/RustFn.fst, test/Rustfn.fst
See the comments in the diff -- this unblocks you @gebner but if you have a function that takes a mutable reference then the mutability of the borrow will be inferred incorrectly.
=> Support for local function calls in MiniRust AST -- this fixes #581

lib/AstToMiniRust.ml, test/RustAbbrev.fst, test/Rustabbrev.fst
=> Fix type abbreviations without lifetimes

lib/PrintMiniRust.ml, test/Rustfn.fst
The Rust printer used to format a call to a function field as `x.f()`.  But that is a method call.  The correct syntax is `(x.f)()`.
=> Rust: parenthesize field accesses in calls

lib/OptimizeMiniRust.ml, test/Rustfn3.fst
This implements a MVP for mutability inference in function pointer fields.  It's enough to extract EverCOSE to Rust.  But there's some limitations:
- This is only for function pointers in structures; function pointers passed as arguments etc. are not supported yet.
- Rust does not have variance for mutability, so if you want to assign a function `fn foo(a: &[u32]) -> bool` to a field with type `fn(&mut [u32]) -> bool`, then you need to mark the argument `a` of `foo` as mutable.  This is not implemented yet.
Fixes #590.  See also preceding PR #582.
cc @R1kM
=> Infer mutability in function pointer fields.

lib/PrintMiniRust.ml
Works around an interesting breakage of HACL-rs.
The Rust translation introduces calls to the `krml::unroll_for!` macro. However, the ! character is not considered as a valid identifier character, and will therefore be replaced by a median point whenever `lexical_conventions` is called on the `unroll_for!` name.
After #578, this function is called whenever a name is not part of the globals stored in the environment, which consisted of the top-level declarations, therefore leading to compilation errors.
To solve this, this PR initializes the Rust printing environment with a mapping for "unroll_for!". Note, it is important to add the mapping manually instead of through `register_globals`, as register_globals also cleans up names through `lexical_conventions`.
Note: if we are introducing …
=> Add krml::unroll_for! to MiniRust printing environment

lib/AstToMiniRust.ml, lib/MiniRust.ml, lib/OptimizeMiniRust.ml, lib/PrintMiniRust.ml, test/Rustfn4.fst
Right now we extract function pointers to Rust as follows:
```rust
pub struct s<'a> {
pub r: &'a mut [bool],
pub f: fn(&'a mut [bool]) -> &'a [bool],
}
```
This is very obviously a massive issue, since it forces the type `s` to be invariant in the lifetime `'a`.  This PR changes the extraction to quantify over the lifetime in the function type instead:
```rust
pub struct s<'a> {
pub r: &'a mut [bool],
pub f: for<'a1> fn(&'a1 mut [bool]) -> &'a1 [bool],
}
```
Now the function pointer no longer has any free lifetime variables, and `s` can be the covariant type it wants to be.
=> Ensure covariance of function types

lib/OptimizeMiniRust.ml
Handle the `*atom = e` case in the mutability inference analysis.
=> Add missing case to Rust mutability analysis

book/tutorial/Makefile, krmllib/Makefile, krmllib/dist/generic/FStar_List_Tot_Base.h, test/Makefile, test/rust-val/Makefile, test/rust-val/impl/Makefile
In preparation for F* PR https://github.com/FStarLang/FStar/pull/3861
No other changes required to Karamel to use this optimization.
Removed --ext context_pruning, since that's now the default in F*
=> Enable optimize_let_vc

krmllib/LowStar.Lib.AssocList.fst
An upcoming update to F*'s SMT encoding reveals that this example actually needs one unit of fuel to pass (to unfold LL1.well_formed).
=> Fix to an example, anticipating an F* update

include/krml/internal/types.h, lib/CFlat.ml, lib/Constant.ml, lib/PrintCommon.ml, lib/PrintMiniRust.ml
As the title, support for float & double, namely, `Float32` and `Float64` are added to the `Constant.ml`. Relevant parts are fixed. This is required from the project [Eurydice](https://github.com/AeneasVerif/eurydice).
Question left: where to add the `float32_t` and `float_64_t` definitions? Just adding to Eurydice is fine, but if this is not defined, Krml might be less self-contained.
=> added support for float & double

lib/Ast.ml, lib/Constant.ml
During the C* -> C11 translation, `is_signed` will be called on floating point, and we should not raise error for that. This PR fixed that.
=> Fixed Eurydice error on floating point

include/krml/internal/target.h, include/krml/internal/types.h
The type name should be `float32_t` and `float64_t` instead of `float32` and `float64` --- as generated in Eurydice.
=> rename to pass Eurydice test

lib/AstToCFlat.ml, lib/AstToCStar.ml, lib/Checker.ml, lib/Options.ml, lib/Warn.ml, src/Karamel.ml
This allows to pass -dbt to get a stack trace on an error:
```
$ krml -dbt [..] foo.krml
[...]
This is not a buffer: any
Warning 4 is fatal, exiting.
Stack trace:
Raised at Krml__Checker.checker_error.(fun) in file "lib/Checker.ml", line 85, characters 4-104
Called from Krml__Checker.infer' in file "lib/Checker.ml", line 700, characters 18-37
Called from Krml__Checker.infer in file "lib/Checker.ml", line 527, characters 10-22
Called from Stdlib__List.map in file "list.ml", line 86, characters 15-19
Called from Krml__Checker.infer' in file "lib/Checker.ml", line 776, characters 13-38
Called from Krml__Checker.infer in file "lib/Checker.ml", line 527, characters 10-22
Called from Krml__Checker.infer' in file "lib/Checker.ml", line 638, characters 13-26
Called from Krml__Checker.infer in …
```
=> Introduce -dbt: print a backtrace on an error

lib/DataTypes.ml
This improves code quality by a lot instead of generating cascading if-then-elses.
=> Deal with Eurydice producing `Enum`s from the get-go

lib/Checker.ml
In the following code : 
https://github.com/FStarLang/karamel/blob/d3f05e518a1d9aeee3acfa596c5bf205d6383cb0/lib/Checker.ml#L867-L879
I think we should substitute the cgs before the types. Because the types may include cgs comming from the current env, which maybe subtituted again by `subst_ctn'`. Thus cause a type mismatch fail. This actually happens when I testing the `[T;C] -> arr<T,C>` translation of arrays in Eurydice on the test case 'where_clauses_fncg.rs'.
I notice that here you actually runs `subst_ctn` before `subst_tn` with some debug infos:
https://github.com/FStarLang/karamel/blob/d3f05e518a1d9aeee3acfa596c5bf205d6383cb0/lib/Checker.ml#L588-L595
So I guess that maybe you've once triggered this bug and fixed it here. But the other cases in this file are not changed. This's why …
=> Substitute cgs before types for all cases in Checker.ml

lib/AstToCFlat.ml, lib/AstToCStar.ml, lib/CStarToC11.ml, lib/GenCtypes.ml, lib/GlobalNames.ml, lib/GlobalNames.mli, lib/Output.ml, lib/Simplify.ml
krml previously considered that all (global) names live in a single namespace, meaning that there were spurious name collisions (for instance, between the case of an enum and a type) as well as missed collisions (because things that are sent to macros end up colliding with everything else)
this overhauls the name management infrastructure (the GlobalNames module) to distinguish three pseudo-namespaces:
- macros
- types
- other declarations (value namespace)
macros conflict with types and other declarations, while type and other declarations do not conflict with each other
this solves a problem exercised by Eurydice while trying to extract Rust's core::fmt::rt namespace
=> Improve name management

lib/AstToCStar.ml, lib/Monomorphization.ml
Various small fixes:
- incorrect order of substitutions
- incorrect recursion that still allowed a partially-monomorphized type, this was not supposed to happen
This required refining the criterion for determining whether an argument is a closed term or not.
CC @Lin23299
=> Fix issue uncovered by AeneasVerif/eurydice#252

lib/Helpers.ml
I hit this in some weird combination of noextract / inline_for_extraction attributes. Just making the error more informative.
=> Nit: more expressive error instead of assert false

lib/CStarToC11.ml
Comes from eurydice PR https://github.com/AeneasVerif/eurydice/pull/252.
=> Added case for compound literal in [trim_trailing_zeros]

lib/CStarToC11.ml
Via aeneasverif/eurydice#252 -- this improves code quality even further
https://github.com/cryspen/libcrux/commit/4405730c2d51fe78ba0579a728875e36f997c1b6
CC @franziskuskiefer for the effect on libcrux
=> Use { 0 } for arrays within compound literals too

.github/workflows/ci.yml
There is currently a problem with OCaml's pprintast/ppxlib in that it generates "raw identifiers" like `\#module` which are not valid in OCaml below 5.2.0
See https://github.com/ocaml/opam-repository/pull/28610#issuecomment-3362301901 for some discussion.
I think this will be fixed upstream, but bumping to OCaml 5.3.0 seems useful anyway. (We can also work around it by using `" module"` instead of `"module"` in lib/GenCtypes.ml, but that's nasty.)
PS. I looked at adding a Nix CI, but adding `checkPhase = "make test"` didn't work for me. I also have no idea how to change the dependencies such as this OCaml version, so I would leave changing the CI to someone else.
=> CI: Use OCaml 5.3.0
